# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Playwright tests

on:
  # Runs on push or pull requests and nightly
  push:
  pull_request:
  schedule:
    # nightly
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install ci
        run: cd static-site && yarn add ci
      - name: Install dependencies
        run: cd static-site && yarn ci
      - name: Install Playwright
        run: cd static-site && npx playwright install --with-deps
      - name: Build production build
        run: cd static-site && yarn build
      - name: Run your tests
        run: cd static-site && yarn test:ui
